/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ScamType = IDL.Variant({
  'other' : IDL.Null,
  'fakeTechSupport' : IDL.Null,
  'ransomware' : IDL.Null,
  'investment' : IDL.Null,
  'phishing' : IDL.Null,
  'identityTheft' : IDL.Null,
  'shopping' : IDL.Null,
  'romance' : IDL.Null,
});
export const Time = IDL.Int;
export const ScamReport = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'authorId' : IDL.Principal,
  'description' : IDL.Text,
  'scamType' : ScamType,
  'dateReported' : Time,
  'lossAmount' : IDL.Opt(IDL.Nat),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createScamReport' : IDL.Func(
      [ScamType, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'getAllReports' : IDL.Func([], [IDL.Vec(ScamReport)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getReportsByType' : IDL.Func([ScamType], [IDL.Vec(ScamReport)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ScamType = IDL.Variant({
    'other' : IDL.Null,
    'fakeTechSupport' : IDL.Null,
    'ransomware' : IDL.Null,
    'investment' : IDL.Null,
    'phishing' : IDL.Null,
    'identityTheft' : IDL.Null,
    'shopping' : IDL.Null,
    'romance' : IDL.Null,
  });
  const Time = IDL.Int;
  const ScamReport = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'authorId' : IDL.Principal,
    'description' : IDL.Text,
    'scamType' : ScamType,
    'dateReported' : Time,
    'lossAmount' : IDL.Opt(IDL.Nat),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createScamReport' : IDL.Func(
        [ScamType, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'getAllReports' : IDL.Func([], [IDL.Vec(ScamReport)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getReportsByType' : IDL.Func([ScamType], [IDL.Vec(ScamReport)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };